<?php if (isset($flash['success'])): ?>
    <?php foreach ($flash['success'] as $flash): ?>
        <div class="success">
            <?= $flash ?>
        </div>
    <?php endforeach ?>
<?php endif ?>
<form action="/users" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <input type="submit" value="Search" />
</form>

<?php foreach ($users as $user): ?>
    <div>
        <?= $user['nickname'] ?>
        <?= $user['id'] ?>
        <form action="/users/<?= $user['id'] ?>" method="post">
            <input type="hidden" name="_METHOD" value="DELETE">
            <input type="submit" value="Remove">
        </form>
    </div>
<?php endforeach ?>

<div>
    <?php if ($page['prev'] > 0):?>
        <a href="/users?page=<?=$page['prev']?>">назад</a>
    <?php endif ?>
    <a href="/users?page=<?=$page['next']?>">вперёд</a>
</div>
