<!-- BEGIN (write your solution here) -->
<form action="/users" method="post">
    <div>
        <label>
            Имя пользователя
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>">
        </label>
        <?php if (isset($errors['nickname'])): ?>
            <div><?= $errors['nickname'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            E-mail
            <input type="text" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
        </label>
        <?php if (isset($errors['email'])): ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Создать">
</form>
<!-- END -->
